[zcash]
pname = "zcash"
version = "FIXME_UNKNOWN_VERSION"
fallbackUrl = "https://download.z.cash/depends-sources"

[nixpkgs]
gitrev = "61525137fd1002f6f2a5eb0ea27d480713362cd5"
sha256 = "af1e8b2d59dc62a0a105554da29458eed9f9f5a3f8a8fa8d8ec031b765fafcbf"

[dependencies.bdb]
version = "6.2.23"
archive = "db-6.2.23.tar.gz"
urlbase = "https://download.oracle.com/berkeley-db/"
sha256 = "47612c8991aa9ac2f6be721267c8d3cdccf5ac83105df8e50809daea24e95dc7"
buildscript = true
configureFlags = [
  "--disable-shared",
  "--enable-cxx",
  "--disable-replication",
  "--with-pic", # FIXME: linux-gnu specific.
  "CXXFLAGS=-std=c++11",
]
makeFlags = [
  "libdb_cxx-6.2.a",
  "libdb-6.2.a",
]

[dependencies.boost]
version = "1.70.0"
archive = "boost_1_70_0.tar.bz2"
urlbase = "https://dl.bintray.com/boostorg/release/1.70.0/source/"
sha256 = "430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778"
configureFlags = [
  "variant=release", # FIXME: un-hardcode variant?
  "--layout=system",
  "threading=multi",
  "link=static",
  "-sNO_BZIP2=1",
  "-sNO_ZLIB=1",
  "threadapi=pthread", # FIXME: linux-gnu specific.
  "runtime-link=shared", # FIXME: linux-gnu specific.
]

# FIXME: not implemented!
#cxxflags = [
#  "-std=c++11",
#  "-fvisibility=hidden",
#  "-fPIC", # FIXME: linux-gnu specific.
#];

patches = [
  # FIXME: Should this be applied on all build platforms?
  "darwin.diff",
]
nativeBuildInputs = [
  "which",
]
buildscript = true

[dependencies.boost.extraEnv]
boostlibs = "chrono,filesystem,program_options,system,thread,test"

[dependencies.googletest]
version = "1.8.0"
source = "github"
sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8"
buildscript = true

[dependencies.googletest.extraEnv]
CXXFLAGS = [
  "-std=c++11",
  # FIXME: -fPIC is specific to some platforms.
  "-fPIC",
]

[dependencies.libevent]
version = "2.1.8"
source = "github"
sha256 = "316ddb401745ac5d222d7c529ef1eada12f58f6376a66c1118eee803cb70f83d"
configureFlags = [
  "--disable-shared",
  "--disable-openssl",
  "--disable-libevent-regress",
  "--with-pic", # FIXME: platform specific to *-*-linux-gnu
  # FIXME: handle removing this hardcoding to match ./depends?
  "--disable-debug-mode",
]
patches = [
  "detect-arch4random_addrandom.patch",
  "detect-arch4random_addrandom-fix.patch",
]

[dependencies.libsodium]
version = "1.0.18"
urlbase = "https://download.libsodium.org/libsodium/releases/"
sha256 = "6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1"
patches = [
  "1.0.15-pubkey-validation.diff",
  "1.0.15-signature-validation.diff",
]
configureFlags = [
  "--enable-static",
  "--disable-shared",
]

[dependencies.native_rust]
# FIXME: This is hardcoded to linux-gnu binaries.
version = "1.44.1"
urlbase = "https://static.rust-lang.org/dist/"
archive = "rust-1.44.1-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "a41df89a461a580536aeb42755e43037556fba2e527dd13a1e1bb0749de28202"
buildscript = true
nativeBuildInputs = [ "file" ]

[dependencies.openssl]
version = "1.1.1a"
urlbase = "https://www.openssl.org/source/old/1.1.1/"
sha256 = "fc20130f8b7cbd2fb918b2f14e2f429e109c31ddd0fb38fc5d71d9ffed3f9f41"

configureFlags = [
  "no-afalgeng",
  "no-asm",
  "no-async",
  "no-bf",
  "no-blake2",
  "no-camellia",
  "no-capieng",
  "no-cast",
  "no-chacha",
  "no-cmac",
  "no-cms",
  "no-comp",
  "no-crypto-mdebug",
  "no-crypto-mdebug-backtrace",
  "no-ct",
  "no-des",
  "no-dgram",
  "no-dsa",
  "no-dso",
  "no-dtls",
  "no-dtls1",
  "no-dtls1-method",
  "no-dynamic-engine",
  "no-ec2m",
  "no-ec_nistp_64_gcc_128",
  "no-egd",
  "no-engine",
  "no-err",
  "no-gost",
  "no-heartbeats",
  "no-idea",
  "no-md2",
  "no-md4",
  "no-mdc2",
  "no-multiblock",
  "no-nextprotoneg",
  "no-ocb",
  "no-ocsp",
  "no-poly1305",
  "no-posix-io",
  "no-psk",
  "no-rc2",
  "no-rc4",
  "no-rc5",
  "no-rdrand",
  "no-rfc3779",
  "no-rmd160",
  "no-scrypt",
  "no-sctp",
  "no-seed",
  "no-shared",
  "no-sock",
  "no-srp",
  "no-srtp",
  "no-ssl",
  "no-ssl3",
  "no-ssl3-method",
  "no-ssl-trace",
  "no-stdio",
  "no-tls",
  "no-tls1",
  "no-tls1-method",
  "no-ts",
  "no-ui",
  "no-unit-test",
  "no-weak-ssl-ciphers",
  "no-whirlpool",
  "no-zlib",
  "no-zlib-dynamic",
  # FIXME: not handled from ./depends:
  # $($(package)_cflags) $($(package)_cppflags),
  "-DPURIFY",
  # linux-gnu specific:
  "-fPIC",
  "-Wa,--noexecstack",
  # x86_64 linux-gnu specific:
  "linux-x86_64",
]

makeFlags = [
  "build_libs",
  "libcrypto.pc",
  "libssl.pc",
  "openssl.pc",
]

nativeBuildInputs = [
  "perl",
]

buildscript = true

[dependencies.utfcpp]
version = "3.1"
source = "github"
sha256 = "ab531c3fd5d275150430bfaca01d7d15e017a188183be932322f2f651506b096"
buildscript = true
