[zcash]
pname = "zcash"
version = "FIXME_UNKNOWN_VERSION"
fallbackUrl = "https://download.z.cash/depends-sources"

[nixpkgs]
gitrev = "61525137fd1002f6f2a5eb0ea27d480713362cd5"
sha256 = "af1e8b2d59dc62a0a105554da29458eed9f9f5a3f8a8fa8d8ec031b765fafcbf"

[dependencies.bdb]
version = "6.2.23"
archive = "db-6.2.23.tar.gz"
urlbase = "https://download.oracle.com/berkeley-db/"
sha256 = "47612c8991aa9ac2f6be721267c8d3cdccf5ac83105df8e50809daea24e95dc7"
buildscript = true
configureFlags = [
  "--disable-shared",
  "--enable-cxx",
  "--disable-replication",
  "--with-pic", # FIXME: linux-gnu specific.
  "CXXFLAGS=-std=c++11",
]
makeFlags = [
  "libdb_cxx-6.2.a",
  "libdb-6.2.a",
]

[dependencies.boost]
version = "1.70.0"
archive = "boost_1_70_0.tar.bz2"
urlbase = "https://dl.bintray.com/boostorg/release/1.70.0/source/"
sha256 = "430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778"
configureFlags = [
  "variant=release", # FIXME: un-hardcode variant?
  "--layout=system",
  "threading=multi",
  "link=static",
  "-sNO_BZIP2=1",
  "-sNO_ZLIB=1",
  "threadapi=pthread", # FIXME: linux-gnu specific.
  "runtime-link=shared", # FIXME: linux-gnu specific.
]

# FIXME: not implemented!
#cxxflags = [
#  "-std=c++11",
#  "-fvisibility=hidden",
#  "-fPIC", # FIXME: linux-gnu specific.
#];

patches = [
  # FIXME: Should this be applied on all build platforms?
  "darwin.diff",
]
nativeBuildInputs = [
  "which",
]
buildscript = true

[dependencies.boost.extraEnv]
boostlibs = "chrono,filesystem,program_options,system,thread,test"

[dependencies.googletest]
version = "1.8.0"
source = "github"
sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8"
buildscript = true

[dependencies.googletest.extraEnv]
CXXFLAGS = [
  "-std=c++11",
  # FIXME: -fPIC is specific to some platforms.
  "-fPIC",
]

[dependencies.libevent]
version = "2.1.8"
source = "github"
sha256 = "316ddb401745ac5d222d7c529ef1eada12f58f6376a66c1118eee803cb70f83d"
configureFlags = [
  "--disable-shared",
  "--disable-openssl",
  "--disable-libevent-regress",
  "--with-pic", # FIXME: platform specific to *-*-linux-gnu
  # FIXME: handle removing this hardcoding to match ./depends?
  "--disable-debug-mode",
]
patches = [
  "detect-arch4random_addrandom.patch",
  "detect-arch4random_addrandom-fix.patch",
]

[dependencies.libsodium]
version = "1.0.18"
urlbase = "https://download.libsodium.org/libsodium/releases/"
sha256 = "6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1"
patches = [
  "1.0.15-pubkey-validation.diff",
  "1.0.15-signature-validation.diff",
]
configureFlags = [
  "--enable-static",
  "--disable-shared",
]

[dependencies.utfcpp]
version = "3.1"
source = "github"
sha256 = "ab531c3fd5d275150430bfaca01d7d15e017a188183be932322f2f651506b096"
buildscript = true

[[sources]]
url = "https://static.rust-lang.org/dist/rust-1.44.1-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "a41df89a461a580536aeb42755e43037556fba2e527dd13a1e1bb0749de28202"

#[[sources]] # FIXME Not yet supported:
#url = "https://static.rust-lang.org/dist/rust-1.44.1-x86_64-apple-darwin"
#sha256 = "a5464e7bcbce9647607904a4afa8362382f1fc55d39e7bbaf4483ac00eb5d56a"
#
#[[sources]] # FIXME Not yet supported:
#url = "https://static.rust-lang.org/dist/rust-1.44.1-x86_64-unknown-freebsd"
#sha256 = "36a14498f9d1d7fb50d6fc01740960a99aff3d4c4c3d2e4fff2795ac8042c957"

[[sources]]
url = "https://www.openssl.org/source/old/1.1.1/openssl-1.1.1a.tar.gz"
sha256 = "fc20130f8b7cbd2fb918b2f14e2f429e109c31ddd0fb38fc5d71d9ffed3f9f41"
