version = "6.2.23"
url = "https://download.oracle.com/berkeley-db/db-6.2.23.tar.gz"
sha256 = "47612c8991aa9ac2f6be721267c8d3cdccf5ac83105df8e50809daea24e95dc7"
configureFlags = [
  "--disable-shared",
  "--enable-cxx",
  "--disable-replication",
  "--with-pic", # FIXME: linux-gnu specific.
  "CXXFLAGS=-std=c++11",
]
makeFlags = [
  "libdb_cxx-6.2.a",
  "libdb-6.2.a",
]
