version = "1.74.0"
archive = "boost_1_74_0.tar.bz2"
urlbase = "https://dl.bintray.com/boostorg/release/1.74.0/source/"
sha256 = "83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1"
configureFlags = [
  "variant=release", # FIXME: un-hardcode variant?
  "--layout=system",
  "threading=multi",
  "link=static",
  "-sNO_BZIP2=1",
  "-sNO_ZLIB=1",
  "threadapi=pthread", # FIXME: linux-gnu specific.
  "runtime-link=shared", # FIXME: linux-gnu specific.
]
patches = [
  "signals2-noise.patch",
]
nativeBuildInputs = [
  "which",
]

[extraEnv]
boostlibs = "chrono,filesystem,program_options,system,thread,test"
cxxFlags = [
  "-std=c++11",
  "-fvisibility=hidden",
  "-fPIC", # FIXME: linux-gnu specific.
]
