image: docker:stable

stages:
  - build
  - test

# To set variables:
# Our organizing principles are:
# (0) the value of a variable should be easily understood by reading this assignment section
# (1) where possible more composed variables should be assembled by concatenation of their atoms
#
# The rationale for (1) is that, more atomic variables are less likely to change, and are more
# likely to be more used (this is because less atomic variables are likely just compositions of
# atomic variables); AND by explicitly being composed in this section their values are more readily
# understood (read) in this context.
#
# where possible add a comment with an example on the variable binding line (especially in more
# atomic cases).
variables:              
  #                     registry.gitlab.com/zingo-labs/zcash
  IMAGE_BASE:           $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  BUILD_CONFIGS_PATH:   $CI_BUILDS_DIR/continuous_integration/gitlab/build_configs

debianbuild:
  stage: build
  variables:
    dockerfile: $CI_BUILDS_DIR/$CI_JOB_NAME
  script:
      - echo $IMAGE_BASE
      - echo $CI_JOB_NAME
      - docker build -t $IMAGE_BASE-$CI_JOB_NAME:$CI_COMMIT_SHA -f $CI_BUILDS_DIR/contrib/ 


test1:
  stage: test
  script:
      - docker run registry.gitlab.com/zingo-labs/zcash/debian_latest_build:latest ls -l ./
      - docker run registry.gitlab.com/zingo-labs/zcash/debian_latest_build:latest ./zcash/qa/zcash/full_test_suite.py
