image: docker:stable

stages:
  - build
  - test

# To set variables:
# Our organizing principles are:
# (0) the value of a variable should be easily understood by reading this assignment section
# (1) where possible more composed variables should be assembled by concatenation of their atoms
#
# The rationale for (1) is that, more atomic variables are less likely to change, and are more
# likely to be more used (this is because less atomic variables are likely just compositions of
# atomic variables); AND by explicitly being composed in this section their values are more readily
# understood (read) in this context.
#
# where possible add a comment with an example on the variable binding line (especially in more
# atomic cases).
variables:              
  #                     registry.gitlab.com/zingo-labs/zcash
  IMAGE_BASE:           $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  BUILD_CONFIGS_PATH:   ./continuous_integration/gitlab/stages/build/
  DEBIANIMAGETAG:       $CI_PROJECT_PATH_SLUG-debian:$CI_COMMIT_SHA 

debianbuild:
  stage: build
  tags:
    - debian
  variables:
    Dockerfile: $BUILD_CONFIGS_PATH/$CI_JOB_NAME/Dockerfile
  script:
      - docker build -t $DEBIANIMAGETAG-base -f $Dockerfile .
      - docker build --no-cache -t $DEBIANIMAGETAG -f $Dockerfile.newcommit .
      - docker login registry.gitlab.com
      - docker push $IMAGE_BASE/$DEBIANIMAGETAG


test1:
  stage: test
  tags:
    - debian
  script:
      - echo $DEBIANIMAGETAG
      - docker run $DEBIANIMAGETAG /zcash/qa/pull-tester/rpc-tests.sh paymentdisclosure.py
