version = "1.70.0"
archive = "boost_1_70_0.tar.bz2"
urlbase = "https://dl.bintray.com/boostorg/release/1.70.0/source/"
sha256 = "430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778"
configureFlags = [
  "variant=release", # FIXME: un-hardcode variant?
  "--layout=system",
  "threading=multi",
  "link=static",
  "-sNO_BZIP2=1",
  "-sNO_ZLIB=1",
  "threadapi=pthread", # FIXME: linux-gnu specific.
  "runtime-link=shared", # FIXME: linux-gnu specific.
]

# FIXME: not implemented!
#cxxflags = [
#  "-std=c++11",
#  "-fvisibility=hidden",
#  "-fPIC", # FIXME: linux-gnu specific.
#];

patches = [
  # FIXME: Should this be applied on all build platforms?
  "darwin.diff",
]
nativeBuildInputs = [
  "which",
]
buildscript = true

[extraEnv]
boostlibs = "chrono,filesystem,program_options,system,thread,test"
