version = "1.8.0"
source = "github"
sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8"
buildscript = true

[extraEnv]
CXXFLAGS = [
  "-std=c++11",
  # FIXME: -fPIC is specific to some platforms.
  "-fPIC",
]

