version = "2.1.8"
source = "github"
sha256 = "316ddb401745ac5d222d7c529ef1eada12f58f6376a66c1118eee803cb70f83d"
nativeBuildInputs = [
  "autoreconfHook",
]
configureFlags = [
  "--disable-shared",
  "--disable-openssl",
  "--disable-libevent-regress",
  "--with-pic", # FIXME: platform specific to *-*-linux-gnu
  # FIXME: handle removing this hardcoding to match ./depends?
  "--disable-debug-mode",
]
patches = [
  "detect-arch4random_addrandom.patch",
  "detect-arch4random_addrandom-fix.patch",
]
