version = "1.0.18"
urlbase = "https://download.libsodium.org/libsodium/releases/"
sha256 = "6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1"
patches = [
  "1.0.15-pubkey-validation.diff",
  "1.0.15-signature-validation.diff",
]
configureFlags = [
  "--enable-static",
  "--disable-shared",
]
